### ISSUE TITLE
Update positions of icons and spinner in the form-field

### ISSUE THREAD

**Issue by stLmpp** [stLmpp/biomercs#61]
After the https://github.com/stLmpp/biomercs-ng/commit/4fc0d3409fb35929cf44152e1eb65db3c1f3c011 the icons in the form-fields are kind of wrong positioned.
They are too much to the right

![image](https://user-images.githubusercontent.com/37917090/122216438-c9b3b480-ce82-11eb-99b4-1b75b11502d0.png)
![image](https://user-images.githubusercontent.com/37917090/122216567-ec45cd80-ce82-11eb-8123-62e1eb12fd96.png)

**Comment by karinamelo26** [comment]
Closed by https://github.com/stLmpp/biomercs-ng/commit/d690bfb01f9519ed1a7f05b2793acadf3fcc2d5d
